<?php
/**
 * AgencyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Financial representative API
 *
 * API for pulling information on FRs
 *
 * OpenAPI spec version: 13a2629d2e525f48315447733f74e466e785cee9
 * Contact: kyle_mcmullen@glic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AgencyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AgencyApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addLeadWithAgency
     *
     * .
     *
     */
    public function testAddLeadWithAgency()
    {

    }

    /**
     * Test case for findLocationByPermalink
     *
     * .
     *
     */
    public function testFindLocationByPermalink()
    {

    }

    /**
     * Test case for findLocations
     *
     * .
     *
     */
    public function testFindLocations()
    {

    }

    /**
     * Test case for getAgencies
     *
     * .
     *
     */
    public function testGetAgencies()
    {

    }

    /**
     * Test case for getAgenciesByLocation
     *
     * .
     *
     */
    public function testGetAgenciesByLocation()
    {

    }

    /**
     * Test case for getAgency
     *
     * .
     *
     */
    public function testGetAgency()
    {

    }

    /**
     * Test case for getLeadAssignableAgencies
     *
     * .
     *
     */
    public function testGetLeadAssignableAgencies()
    {

    }

    /**
     * Test case for selectLocations
     *
     * .
     *
     */
    public function testSelectLocations()
    {

    }

    /**
     * Test case for updateAgency
     *
     * .
     *
     */
    public function testUpdateAgency()
    {

    }

    /**
     * Test case for updateAgencyLogo
     *
     * .
     *
     */
    public function testUpdateAgencyLogo()
    {

    }

    /**
     * Test case for updateLocation
     *
     * .
     *
     */
    public function testUpdateLocation()
    {

    }

}
