<?php
/**
 * LeadApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Financial representative API
 *
 * API for pulling information on FRs
 *
 * OpenAPI spec version: 13a2629d2e525f48315447733f74e466e785cee9
 * Contact: kyle_mcmullen@glic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * LeadApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LeadApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addActivityStatusComment
     *
     * .
     *
     */
    public function testAddActivityStatusComment()
    {

    }

    /**
     * Test case for addLead
     *
     * .
     *
     */
    public function testAddLead()
    {

    }

    /**
     * Test case for addLeadByAlias
     *
     * .
     *
     */
    public function testAddLeadByAlias()
    {

    }

    /**
     * Test case for createService
     *
     * .
     *
     */
    public function testCreateService()
    {

    }

    /**
     * Test case for findLeadById
     *
     * .
     *
     */
    public function testFindLeadById()
    {

    }

    /**
     * Test case for findLeads
     *
     * .
     *
     */
    public function testFindLeads()
    {

    }

    /**
     * Test case for getActivities
     *
     * .
     *
     */
    public function testGetActivities()
    {

    }

    /**
     * Test case for getActivity
     *
     * .
     *
     */
    public function testGetActivity()
    {

    }

    /**
     * Test case for getActivityStatus
     *
     * .
     *
     */
    public function testGetActivityStatus()
    {

    }

    /**
     * Test case for getActivityStatusComments
     *
     * .
     *
     */
    public function testGetActivityStatusComments()
    {

    }

    /**
     * Test case for getAgencyForReassign
     *
     * .
     *
     */
    public function testGetAgencyForReassign()
    {

    }

    /**
     * Test case for getCampaigns
     *
     * .
     *
     */
    public function testGetCampaigns()
    {

    }

    /**
     * Test case for getCommentById
     *
     * .
     *
     */
    public function testGetCommentById()
    {

    }

    /**
     * Test case for getComments
     *
     * .
     *
     */
    public function testGetComments()
    {

    }

    /**
     * Test case for getLeadActivityStatuses
     *
     * .
     *
     */
    public function testGetLeadActivityStatuses()
    {

    }

    /**
     * Test case for getLeadQuiz
     *
     * .
     *
     */
    public function testGetLeadQuiz()
    {

    }

    /**
     * Test case for getService
     *
     * .
     *
     */
    public function testGetService()
    {

    }

    /**
     * Test case for getServices
     *
     * .
     *
     */
    public function testGetServices()
    {

    }

    /**
     * Test case for transitionLead
     *
     * .
     *
     */
    public function testTransitionLead()
    {

    }

    /**
     * Test case for updateActivityStatus
     *
     * .
     *
     */
    public function testUpdateActivityStatus()
    {

    }

    /**
     * Test case for updateLead
     *
     * .
     *
     */
    public function testUpdateLead()
    {

    }

    /**
     * Test case for updateLeadDiQuote
     *
     * .
     *
     */
    public function testUpdateLeadDiQuote()
    {

    }

    /**
     * Test case for updateService
     *
     * .
     *
     */
    public function testUpdateService()
    {

    }

}
