<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Financial representative API
 *
 * API for pulling information on FRs
 *
 * OpenAPI spec version: 13a2629d2e525f48315447733f74e466e785cee9
 * Contact: kyle_mcmullen@glic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createDevice
     *
     * .
     *
     */
    public function testCreateDevice()
    {

    }

    /**
     * Test case for currentUser
     *
     * .
     *
     */
    public function testCurrentUser()
    {

    }

    /**
     * Test case for disassociateDevice
     *
     * .
     *
     */
    public function testDisassociateDevice()
    {

    }

    /**
     * Test case for getAgencyUsers
     *
     * .
     *
     */
    public function testGetAgencyUsers()
    {

    }

    /**
     * Test case for getDeviceById
     *
     * .
     *
     */
    public function testGetDeviceById()
    {

    }

    /**
     * Test case for getNotifications
     *
     * .
     *
     */
    public function testGetNotifications()
    {

    }

    /**
     * Test case for getUnreadNotifications
     *
     * .
     *
     */
    public function testGetUnreadNotifications()
    {

    }

    /**
     * Test case for getUserById
     *
     * .
     *
     */
    public function testGetUserById()
    {

    }

    /**
     * Test case for getUserDevices
     *
     * .
     *
     */
    public function testGetUserDevices()
    {

    }

    /**
     * Test case for updateDevice
     *
     * .
     *
     */
    public function testUpdateDevice()
    {

    }

    /**
     * Test case for updateNotification
     *
     * .
     *
     */
    public function testUpdateNotification()
    {

    }

}
