<?php
/**
 * AgencyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Financial representative API
 *
 * API for pulling information on FRs
 *
 * OpenAPI spec version: 13a2629d2e525f48315447733f74e466e785cee9
 * Contact: kyle_mcmullen@glic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AgencyTest Class Doc Comment
 *
 * @category    Class */
// * @description Agency
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AgencyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Agency"
     */
    public function testAgency()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {

    }

    /**
     * Test attribute "permalink"
     */
    public function testPropertyPermalink()
    {

    }

    /**
     * Test attribute "phone_numbers"
     */
    public function testPropertyPhoneNumbers()
    {

    }

    /**
     * Test attribute "web_sites"
     */
    public function testPropertyWebSites()
    {

    }

    /**
     * Test attribute "primary_name"
     */
    public function testPropertyPrimaryName()
    {

    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {

    }

    /**
     * Test attribute "logo_url"
     */
    public function testPropertyLogoUrl()
    {

    }

    /**
     * Test attribute "default_profile"
     */
    public function testPropertyDefaultProfile()
    {

    }

    /**
     * Test attribute "default_disclaimer"
     */
    public function testPropertyDefaultDisclaimer()
    {

    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {

    }

    /**
     * Test attribute "lead_coordinator"
     */
    public function testPropertyLeadCoordinator()
    {

    }

    /**
     * Test attribute "lead_coordinator_username"
     */
    public function testPropertyLeadCoordinatorUsername()
    {

    }

    /**
     * Test attribute "recruiting_contact_username"
     */
    public function testPropertyRecruitingContactUsername()
    {

    }

    /**
     * Test attribute "recruiting_contact"
     */
    public function testPropertyRecruitingContact()
    {

    }

    /**
     * Test attribute "locations"
     */
    public function testPropertyLocations()
    {

    }

    /**
     * Test attribute "phone_numbers_attributes"
     */
    public function testPropertyPhoneNumbersAttributes()
    {

    }

    /**
     * Test attribute "web_sites_attributes"
     */
    public function testPropertyWebSitesAttributes()
    {

    }

}
