<?php
/**
 * ApplicantTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Financial representative API
 *
 * API for pulling information on FRs
 *
 * OpenAPI spec version: 13a2629d2e525f48315447733f74e466e785cee9
 * Contact: kyle_mcmullen@glic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ApplicantTest Class Doc Comment
 *
 * @category    Class */
// * @description Applicant
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApplicantTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Applicant"
     */
    public function testApplicant()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

    /**
     * Test attribute "high_priority"
     */
    public function testPropertyHighPriority()
    {

    }

    /**
     * Test attribute "has_resume"
     */
    public function testPropertyHasResume()
    {

    }

    /**
     * Test attribute "licensed"
     */
    public function testPropertyLicensed()
    {

    }

    /**
     * Test attribute "sponsorship"
     */
    public function testPropertySponsorship()
    {

    }

    /**
     * Test attribute "level_of_experience"
     */
    public function testPropertyLevelOfExperience()
    {

    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {

    }

    /**
     * Test attribute "resume"
     */
    public function testPropertyResume()
    {

    }

    /**
     * Test attribute "current_occupation"
     */
    public function testPropertyCurrentOccupation()
    {

    }

    /**
     * Test attribute "financial_service_experience"
     */
    public function testPropertyFinancialServiceExperience()
    {

    }

    /**
     * Test attribute "licenses"
     */
    public function testPropertyLicenses()
    {

    }

    /**
     * Test attribute "location_ids"
     */
    public function testPropertyLocationIds()
    {

    }

    /**
     * Test attribute "campaign_ids"
     */
    public function testPropertyCampaignIds()
    {

    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {

    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {

    }

    /**
     * Test attribute "phone_numbers"
     */
    public function testPropertyPhoneNumbers()
    {

    }

    /**
     * Test attribute "emails"
     */
    public function testPropertyEmails()
    {

    }

    /**
     * Test attribute "web_sites"
     */
    public function testPropertyWebSites()
    {

    }

}
