<?php
/**
 * DiQuoteTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Financial representative API
 *
 * API for pulling information on FRs
 *
 * OpenAPI spec version: 13a2629d2e525f48315447733f74e466e785cee9
 * Contact: kyle_mcmullen@glic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DiQuoteTest Class Doc Comment
 *
 * @category    Class */
// * @description DiQuote
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DiQuoteTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "DiQuote"
     */
    public function testDiQuote()
    {

    }

    /**
     * Test attribute "premium"
     */
    public function testPropertyPremium()
    {

    }

    /**
     * Test attribute "riders"
     */
    public function testPropertyRiders()
    {

    }

    /**
     * Test attribute "monthly_benefit"
     */
    public function testPropertyMonthlyBenefit()
    {

    }

    /**
     * Test attribute "benefit_period"
     */
    public function testPropertyBenefitPeriod()
    {

    }

    /**
     * Test attribute "elimination_period"
     */
    public function testPropertyEliminationPeriod()
    {

    }

    /**
     * Test attribute "quote_link"
     */
    public function testPropertyQuoteLink()
    {

    }

    /**
     * Test attribute "age"
     */
    public function testPropertyAge()
    {

    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {

    }

    /**
     * Test attribute "income"
     */
    public function testPropertyIncome()
    {

    }

    /**
     * Test attribute "occupation"
     */
    public function testPropertyOccupation()
    {

    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {

    }

}
