<?php
/**
 * InquiryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Financial representative API
 *
 * API for pulling information on FRs
 *
 * OpenAPI spec version: 13a2629d2e525f48315447733f74e466e785cee9
 * Contact: kyle_mcmullen@glic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InquiryTest Class Doc Comment
 *
 * @category    Class */
// * @description Inquiry
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InquiryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Inquiry"
     */
    public function testInquiry()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {

    }

    /**
     * Test attribute "account_number"
     */
    public function testPropertyAccountNumber()
    {

    }

    /**
     * Test attribute "best_time_to_call"
     */
    public function testPropertyBestTimeToCall()
    {

    }

    /**
     * Test attribute "customer_note"
     */
    public function testPropertyCustomerNote()
    {

    }

    /**
     * Test attribute "inquiry_topic_id"
     */
    public function testPropertyInquiryTopicId()
    {

    }

    /**
     * Test attribute "inquiry_topic"
     */
    public function testPropertyInquiryTopic()
    {

    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {

    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {

    }

    /**
     * Test attribute "phone_numbers"
     */
    public function testPropertyPhoneNumbers()
    {

    }

    /**
     * Test attribute "emails"
     */
    public function testPropertyEmails()
    {

    }

}
