<?php
/**
 * LeadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Financial representative API
 *
 * API for pulling information on FRs
 *
 * OpenAPI spec version: 13a2629d2e525f48315447733f74e466e785cee9
 * Contact: kyle_mcmullen@glic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LeadTest Class Doc Comment
 *
 * @category    Class */
// * @description Lead
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LeadTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Lead"
     */
    public function testLead()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "high_priority"
     */
    public function testPropertyHighPriority()
    {

    }

    /**
     * Test attribute "contact_preference"
     */
    public function testPropertyContactPreference()
    {

    }

    /**
     * Test attribute "best_time_to_call"
     */
    public function testPropertyBestTimeToCall()
    {

    }

    /**
     * Test attribute "current_client"
     */
    public function testPropertyCurrentClient()
    {

    }

    /**
     * Test attribute "receive_email_updates"
     */
    public function testPropertyReceiveEmailUpdates()
    {

    }

    /**
     * Test attribute "auto_assign"
     */
    public function testPropertyAutoAssign()
    {

    }

    /**
     * Test attribute "customer_note"
     */
    public function testPropertyCustomerNote()
    {

    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {

    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {

    }

    /**
     * Test attribute "phone_numbers"
     */
    public function testPropertyPhoneNumbers()
    {

    }

    /**
     * Test attribute "emails"
     */
    public function testPropertyEmails()
    {

    }

    /**
     * Test attribute "services"
     */
    public function testPropertyServices()
    {

    }

    /**
     * Test attribute "service_ids"
     */
    public function testPropertyServiceIds()
    {

    }

    /**
     * Test attribute "campaign_ids"
     */
    public function testPropertyCampaignIds()
    {

    }

    /**
     * Test attribute "comments_count"
     */
    public function testPropertyCommentsCount()
    {

    }

    /**
     * Test attribute "recent_comments"
     */
    public function testPropertyRecentComments()
    {

    }

    /**
     * Test attribute "agency"
     */
    public function testPropertyAgency()
    {

    }

    /**
     * Test attribute "di_quote"
     */
    public function testPropertyDiQuote()
    {

    }

}
