<?php
/**
 * LocationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Financial representative API
 *
 * API for pulling information on FRs
 *
 * OpenAPI spec version: 13a2629d2e525f48315447733f74e466e785cee9
 * Contact: kyle_mcmullen@glic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LocationTest Class Doc Comment
 *
 * @category    Class */
// * @description Location
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LocationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Location"
     */
    public function testLocation()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {

    }

    /**
     * Test attribute "phone_number"
     */
    public function testPropertyPhoneNumber()
    {

    }

    /**
     * Test attribute "phone_number_attributes"
     */
    public function testPropertyPhoneNumberAttributes()
    {

    }

    /**
     * Test attribute "address_attributes"
     */
    public function testPropertyAddressAttributes()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

    /**
     * Test attribute "dba_name"
     */
    public function testPropertyDbaName()
    {

    }

    /**
     * Test attribute "permalink"
     */
    public function testPropertyPermalink()
    {

    }

    /**
     * Test attribute "primary_location"
     */
    public function testPropertyPrimaryLocation()
    {

    }

    /**
     * Test attribute "profile"
     */
    public function testPropertyProfile()
    {

    }

    /**
     * Test attribute "disclaimer"
     */
    public function testPropertyDisclaimer()
    {

    }

    /**
     * Test attribute "recruiting"
     */
    public function testPropertyRecruiting()
    {

    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {

    }

}
