<?php
/**
 * LogoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Financial representative API
 *
 * API for pulling information on FRs
 *
 * OpenAPI spec version: 13a2629d2e525f48315447733f74e466e785cee9
 * Contact: kyle_mcmullen@glic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LogoTest Class Doc Comment
 *
 * @category    Class */
// * @description Logo
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LogoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Logo"
     */
    public function testLogo()
    {

    }

    /**
     * Test attribute "small"
     */
    public function testPropertySmall()
    {

    }

    /**
     * Test attribute "large"
     */
    public function testPropertyLarge()
    {

    }

    /**
     * Test attribute "original"
     */
    public function testPropertyOriginal()
    {

    }

    /**
     * Test attribute "thumbnail"
     */
    public function testPropertyThumbnail()
    {

    }

    /**
     * Test attribute "medium"
     */
    public function testPropertyMedium()
    {

    }

}
